### ISSUE TITLE
Typo in outliers

### ISSUE THREAD

**Issue by cedure** [elisemercury/AutoClean#2]
Hi, your work looks great! 
I just ran into an error while giving it a try due to what I guess is a typo in Outliers.handle() in Module.py.
Hope it helps 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/58391728/166934198-ab61448f-bfc0-48bf-89da-07947aa1cfc5.png">

**Comment by elisemercury** [comment]
Hi @cedure! Thanks a lot for noticing - the typo has now been fixed.
