### ISSUE TITLE
setup.py installation issue (missing version.py)

### ISSUE THREAD

**Issue by rroline** [elisemercury/AutoClean#9]
When attempting to install this package, the following error is received. There seems to be an issue with the reference when looking for the version.py file. Unusually enough, I was able to install it on my macos just fine, but install on a linux server (Ubuntu) fails. This is an amazing project and any help would be greatly appreciated. 

`user:~$ pip install py-AutoClean
Defaulting to user installation because normal site-packages is not writeable
Collecting py-AutoClean
  Using cached py-AutoClean-1.1.2.tar.gz (10.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dur0zqvq/py-autoclean_38a9561f558e44998731363c207c9b15/setup.py", line 9, in <module>
          exec(open('autoclean/version.py').read())
      FileNotFoundError: [Errno 2] No such file or directory: 'autoclean/version.py'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by elisemercury** [comment]
Hi @rroline,
Thanks a lot for your feedback!
I fixed this issue in the new release v1.1.3. Now the `version.py` file dependency is completely removed, so there should be no more issues coming up with that.
Again thanks and all the best
Elise

**Comment by rroline** [comment]
> Hi @rroline, Thanks a lot for your feedback! I fixed this issue in the new release v1.1.3. Now the `version.py` file dependency is completely removed, so there should be no more issues coming up with that. Again thanks and all the best Elise

You are a rockstar! Thank you so much! This is such a great project - I just couldn't stand to not use it. Appreciate the responsiveness and willingness to help!
